'use client';

import React, { useState, useEffect } from 'react';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Plus,
  Link as LinkIcon,
  MapPin,
  Calendar,
  Clock,
  Copy,
  QrCode,
  Loader2,
  CheckCircle,
  XCircle,
  Trash2,
  Eye,
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { format, parseISO } from 'date-fns';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { GoogleLocationPicker } from './google-location-picker';

interface AttendanceLink {
  id: string;
  link_code: string;
  title: string;
  target_latitude: number;
  target_longitude: number;
  allowed_radius_meters: number;
  valid_from: string;
  valid_until: string;
  is_active: boolean;
  max_uses: number | null;
  current_uses: number;
  auto_generate_daily: boolean;
  url: string;
  qr_code_data: string;
  created_by_user?: {
    full_name: string;
    email: string;
  };
  office_location?: {
    name: string;
    address: string;
  };
}

interface OfficeLocation {
  id: string;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  radius_meters: number;
}

export function AttendanceLinkManager() {
  const [links, setLinks] = useState<AttendanceLink[]>([]);
  const [officeLocations, setOfficeLocations] = useState<OfficeLocation[]>([]);
  const [loading, setLoading] = useState(true);
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [creating, setCreating] = useState(false);
  const { toast } = useToast();

  // Form state
  const [title, setTitle] = useState('');
  const [selectedOfficeLocation, setSelectedOfficeLocation] =
    useState<string>('');
  const [customLatitude, setCustomLatitude] = useState('');
  const [customLongitude, setCustomLongitude] = useState('');
  const [googleLocation, setGoogleLocation] = useState<{
    latitude: number;
    longitude: number;
    address: string;
    name?: string;
  } | null>(null);
  const [locationSource, setLocationSource] = useState<
    'office' | 'google' | 'custom'
  >('google');
  const [allowedRadius, setAllowedRadius] = useState('50');
  const [validUntil, setValidUntil] = useState('');
  const [maxUses, setMaxUses] = useState('');
  const [autoGenerateDaily, setAutoGenerateDaily] = useState(false);

  useEffect(() => {
    fetchLinks();
    fetchOfficeLocations();
  }, []);

  const fetchLinks = async () => {
    try {
      const response = await fetch('/api/employer/attendance-links');
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to fetch links');
      }

      setLinks(data.links || []);
    } catch (error: any) {
      toast({
        title: 'Error',
        description: error.message || 'Failed to load attendance links',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  const fetchOfficeLocations = async () => {
    try {
      const response = await fetch('/api/employer/office-locations');
      const data = await response.json();

      if (response.ok && data.locations) {
        setOfficeLocations(data.locations);
      }
    } catch (error) {
    }
  };

  const handleCreateLink = async () => {
    try {
      setCreating(true);

      // Determine coordinates
      let latitude: number;
      let longitude: number;
      let officeLocationId: string | null = null;

      if (locationSource === 'office' && selectedOfficeLocation) {
        // Use office location coordinates
        const office = officeLocations.find(
          loc => loc.id === selectedOfficeLocation
        );
        if (!office) {
          throw new Error('Selected office location not found');
        }
        latitude = office.latitude;
        longitude = office.longitude;
        officeLocationId = office.id;
      } else if (locationSource === 'google' && googleLocation) {
        // Use Google Maps location
        latitude = googleLocation.latitude;
        longitude = googleLocation.longitude;
      } else if (locationSource === 'custom') {
        // Use custom coordinates
        latitude = parseFloat(customLatitude);
        longitude = parseFloat(customLongitude);

        if (isNaN(latitude) || isNaN(longitude)) {
          throw new Error('Please provide valid coordinates');
        }
      } else {
        throw new Error('Please select a location');
      }

      if (!validUntil) {
        throw new Error('Please set an expiration date');
      }

      const response = await fetch('/api/employer/attendance-links', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: title || `Check-In Link - ${new Date().toLocaleDateString()}`,
          target_latitude: latitude,
          target_longitude: longitude,
          allowed_radius_meters: parseInt(allowedRadius) || 50,
          valid_until: validUntil,
          max_uses: maxUses ? parseInt(maxUses) : null,
          auto_generate_daily: autoGenerateDaily,
          office_location_id: officeLocationId,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to create link');
      }

      toast({
        title: '✅ Link Created',
        description: 'Attendance check-in link has been created successfully',
      });

      // Reset form
      setTitle('');
      setSelectedOfficeLocation('');
      setCustomLatitude('');
      setCustomLongitude('');
      setGoogleLocation(null);
      setLocationSource('google');
      setAllowedRadius('50');
      setValidUntil('');
      setMaxUses('');
      setAutoGenerateDaily(false);
      setShowCreateDialog(false);

      fetchLinks();
    } catch (error: any) {
      toast({
        title: 'Error',
        description: error.message || 'Failed to create link',
        variant: 'destructive',
      });
    } finally {
      setCreating(false);
    }
  };

  const copyLink = (url: string) => {
    navigator.clipboard.writeText(url);
    toast({
      title: 'Copied!',
      description: 'Link copied to clipboard',
    });
  };

  const isLinkExpired = (validUntil: string) => {
    return new Date(validUntil) < new Date();
  };

  const isLinkActive = (link: AttendanceLink) => {
    const now = new Date();
    return (
      link.is_active &&
      now >= new Date(link.valid_from) &&
      now <= new Date(link.valid_until) &&
      (!link.max_uses || link.current_uses < link.max_uses)
    );
  };

  if (loading) {
    return (
      <Card>
        <CardContent className='flex items-center justify-center py-12'>
          <Loader2 className='h-8 w-8 animate-spin text-primary' />
        </CardContent>
      </Card>
    );
  }

  return (
    <div className='space-y-6'>
      <div className='flex items-center justify-between'>
        <div>
          <h2 className='text-2xl font-bold'>Attendance Check-In Links</h2>
          <p className='text-sm text-muted-foreground'>
            Create location-restricted check-in links for employees
          </p>
        </div>
        <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
          <DialogTrigger asChild>
            <Button>
              <Plus className='h-4 w-4 mr-2' />
              Create New Link
            </Button>
          </DialogTrigger>
          <DialogContent className='sm:max-w-lg'>
            <DialogHeader>
              <DialogTitle>Create Attendance Check-In Link</DialogTitle>
              <DialogDescription>
                Create a location-restricted link that employees can use to
                check in
              </DialogDescription>
            </DialogHeader>
            <div className='space-y-4'>
              <div>
                <Label htmlFor='title'>Title (Optional)</Label>
                <Input
                  id='title'
                  value={title}
                  onChange={e => setTitle(e.target.value)}
                  placeholder='e.g., Main Office Check-In'
                />
              </div>

              <div>
                <Label htmlFor='location-source'>Location Source</Label>
                <Select
                  value={locationSource}
                  onValueChange={(value: 'office' | 'google' | 'custom') => {
                    setLocationSource(value);
                    if (value !== 'google') {
                      setGoogleLocation(null);
                    }
                    if (value !== 'office') {
                      setSelectedOfficeLocation('');
                    }
                    if (value !== 'custom') {
                      setCustomLatitude('');
                      setCustomLongitude('');
                    }
                  }}
                >
                  <SelectTrigger>
                    <SelectValue placeholder='Select location source' />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value='google'>Google Maps Search</SelectItem>
                    <SelectItem value='office'>Office Location</SelectItem>
                    <SelectItem value='custom'>Custom Coordinates</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {locationSource === 'google' && (
                <GoogleLocationPicker
                  onLocationSelect={location => {
                    setGoogleLocation(location);
                    if (location.name && !title) {
                      setTitle(location.name);
                    }
                  }}
                />
              )}

              {locationSource === 'office' && (
                <div>
                  <Label htmlFor='office-location'>
                    Select Office Location
                  </Label>
                  <Select
                    value={selectedOfficeLocation}
                    onValueChange={setSelectedOfficeLocation}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder='Select an office location' />
                    </SelectTrigger>
                    <SelectContent>
                      {officeLocations.map(loc => (
                        <SelectItem key={loc.id} value={loc.id}>
                          {loc.name} - {loc.address}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {selectedOfficeLocation && (
                    <Alert className='mt-2'>
                      <MapPin className='h-4 w-4' />
                      <AlertDescription>
                        Using coordinates from selected office location
                      </AlertDescription>
                    </Alert>
                  )}
                </div>
              )}

              {locationSource === 'custom' && (
                <div className='grid grid-cols-2 gap-4'>
                  <div>
                    <Label htmlFor='latitude'>Latitude</Label>
                    <Input
                      id='latitude'
                      type='number'
                      step='any'
                      value={customLatitude}
                      onChange={e => setCustomLatitude(e.target.value)}
                      placeholder='23.5859'
                    />
                  </div>
                  <div>
                    <Label htmlFor='longitude'>Longitude</Label>
                    <Input
                      id='longitude'
                      type='number'
                      step='any'
                      value={customLongitude}
                      onChange={e => setCustomLongitude(e.target.value)}
                      placeholder='58.4059'
                    />
                  </div>
                </div>
              )}

              <div>
                <Label htmlFor='radius'>Allowed Radius (meters)</Label>
                <Input
                  id='radius'
                  type='number'
                  value={allowedRadius}
                  onChange={e => setAllowedRadius(e.target.value)}
                  placeholder='50'
                />
                <p className='text-xs text-muted-foreground mt-1'>
                  Employees must be within this distance to check in
                </p>
              </div>

              <div>
                <Label htmlFor='validUntil'>Valid Until</Label>
                <Input
                  id='validUntil'
                  type='datetime-local'
                  value={validUntil}
                  onChange={e => setValidUntil(e.target.value)}
                  required
                />
              </div>

              <div>
                <Label htmlFor='maxUses'>Max Uses (Optional)</Label>
                <Input
                  id='maxUses'
                  type='number'
                  value={maxUses}
                  onChange={e => setMaxUses(e.target.value)}
                  placeholder='Leave empty for unlimited'
                />
              </div>

              <div className='flex items-center space-x-2'>
                <input
                  type='checkbox'
                  id='autoGenerate'
                  checked={autoGenerateDaily}
                  onChange={e => setAutoGenerateDaily(e.target.checked)}
                  className='rounded'
                />
                <Label htmlFor='autoGenerate' className='cursor-pointer'>
                  Auto-generate daily at valid_from time
                </Label>
              </div>

              <div className='flex gap-2'>
                <Button
                  onClick={handleCreateLink}
                  disabled={creating}
                  className='flex-1'
                >
                  {creating ? (
                    <Loader2 className='h-4 w-4 mr-2 animate-spin' />
                  ) : (
                    <Plus className='h-4 w-4 mr-2' />
                  )}
                  Create Link
                </Button>
                <Button
                  variant='outline'
                  onClick={() => setShowCreateDialog(false)}
                >
                  Cancel
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {links.length === 0 ? (
        <Card>
          <CardContent className='flex flex-col items-center justify-center py-12'>
            <LinkIcon className='h-12 w-12 text-muted-foreground mb-4' />
            <p className='text-lg font-medium'>No Links Created</p>
            <p className='text-sm text-muted-foreground'>
              Create your first attendance check-in link to get started
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className='grid gap-4'>
          {links.map(link => (
            <Card
              key={link.id}
              className={!isLinkActive(link) ? 'opacity-60' : ''}
            >
              <CardHeader>
                <div className='flex items-start justify-between'>
                  <div className='flex-1'>
                    <CardTitle className='flex items-center gap-2'>
                      <LinkIcon className='h-5 w-5' />
                      {link.title}
                    </CardTitle>
                    <CardDescription className='mt-1'>
                      {link.office_location?.name || `Custom Location`}
                    </CardDescription>
                  </div>
                  <div className='flex flex-col items-end gap-2'>
                    {isLinkActive(link) ? (
                      <Badge variant='default'>
                        <CheckCircle className='h-3 w-3 mr-1' />
                        Active
                      </Badge>
                    ) : (
                      <Badge variant='secondary'>
                        <XCircle className='h-3 w-3 mr-1' />
                        {isLinkExpired(link.valid_until)
                          ? 'Expired'
                          : 'Inactive'}
                      </Badge>
                    )}
                    {link.auto_generate_daily && (
                      <Badge variant='outline' className='text-xs'>
                        <Clock className='h-3 w-3 mr-1' />
                        Auto Daily
                      </Badge>
                    )}
                  </div>
                </div>
              </CardHeader>
              <CardContent className='space-y-4'>
                <div className='grid grid-cols-2 gap-4 text-sm'>
                  <div>
                    <Label className='text-xs text-muted-foreground'>
                      Location
                    </Label>
                    <p className='font-medium'>
                      {link.target_latitude.toFixed(6)},{' '}
                      {link.target_longitude.toFixed(6)}
                    </p>
                    <p className='text-xs text-muted-foreground'>
                      Radius: {link.allowed_radius_meters}m
                    </p>
                  </div>
                  <div>
                    <Label className='text-xs text-muted-foreground'>
                      Valid Until
                    </Label>
                    <p className='font-medium'>
                      {format(
                        parseISO(link.valid_until),
                        'MMM dd, yyyy hh:mm a'
                      )}
                    </p>
                    {link.max_uses && (
                      <p className='text-xs text-muted-foreground'>
                        Uses: {link.current_uses} / {link.max_uses}
                      </p>
                    )}
                  </div>
                </div>

                <div className='flex items-center gap-2 p-3 bg-gray-50 rounded-lg'>
                  <Input
                    value={link.url}
                    readOnly
                    className='font-mono text-sm'
                  />
                  <Button
                    variant='outline'
                    size='sm'
                    onClick={() => copyLink(link.url)}
                  >
                    <Copy className='h-4 w-4' />
                  </Button>
                  <Button
                    variant='outline'
                    size='sm'
                    onClick={() => window.open(link.url, '_blank')}
                  >
                    <Eye className='h-4 w-4' />
                  </Button>
                </div>

                <div className='flex gap-2'>
                  <Button
                    variant='outline'
                    size='sm'
                    onClick={() => copyLink(link.url)}
                    className='flex-1'
                  >
                    <Copy className='h-4 w-4 mr-2' />
                    Copy Link
                  </Button>
                  <Button
                    variant='outline'
                    size='sm'
                    onClick={() => {
                      // Generate QR code (you can integrate a QR code library)
                      toast({
                        title: 'QR Code',
                        description:
                          'QR code feature coming soon. Use the link for now.',
                      });
                    }}
                    className='flex-1'
                  >
                    <QrCode className='h-4 w-4 mr-2' />
                    QR Code
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
