'use client';

/**
 * Nonce Context for CSP Security
 *
 * Provides a secure nonce value to components that need to render inline scripts/styles
 * with proper Content-Security-Policy compliance.
 *
 * @see CSP_NONCE_IMPLEMENTATION_GUIDE.md for full implementation details
 */

import { createContext, useContext, ReactNode } from 'react';

/**
 * Context for storing the CSP nonce value
 * Undefined by default - must be wrapped in NonceProvider
 */
const NonceContext = createContext<string | undefined>(undefined);

/**
 * Provider component that supplies the nonce to child components
 *
 * @param nonce - The nonce value generated by middleware
 * @param children - React children that will have access to the nonce
 *
 * @example
 * ```tsx
 * // In app/layout.tsx
 * const nonce = headers().get('x-nonce') || '';
 * return (
 *   <NonceProvider nonce={nonce}>
 *     {children}
 *   </NonceProvider>
 * );
 * ```
 */
export function NonceProvider({
  nonce,
  children,
}: {
  nonce: string;
  children: ReactNode;
}) {
  return (
    <NonceContext.Provider value={nonce}>{children}</NonceContext.Provider>
  );
}

/**
 * Hook to access the current CSP nonce value
 *
 * @returns The nonce string for use in script/style nonce attributes
 * @throws Error if used outside of NonceProvider
 *
 * @example
 * ```tsx
 * function MyComponent() {
 *   const nonce = useNonce();
 *   return (
 *     <script
 *       nonce={nonce}
 *       dangerouslySetInnerHTML={{ __html: 'console.log("safe")' }}
 *     />
 *   );
 * }
 * ```
 */
export function useNonce(): string {
  const nonce = useContext(NonceContext);
  if (nonce === undefined) {
    // In development, return empty string to avoid breaking the app
    if (process.env.NODE_ENV === 'development') {
      return '';
    }
    throw new Error('useNonce must be used within NonceProvider');
  }
  return nonce;
}

/**
 * Safe version of useNonce that returns empty string if no provider found
 * Useful for components that work both with and without nonce
 *
 * @returns The nonce string or empty string if not available
 */
export function useNonceSafe(): string {
  const nonce = useContext(NonceContext);
  return nonce ?? '';
}
