-- ========================================
-- 🔐 ENABLE MFA FOR operations@falconeyegroup.net
-- ========================================
-- Date: October 28, 2025
-- Purpose: Enable Two-Factor Authentication for operations@falconeyegroup.net
-- User: Waqas Ahmad
-- User ID: 947d9e41-8d7b-4604-978b-4cb2819b8794
-- ========================================

-- Step 1: Generate TOTP secret and backup codes
-- Note: This is a template - actual secret will be generated by authenticator app

-- Step 2: Insert MFA configuration (pending verification)
INSERT INTO user_mfa (
  user_id,
  totp_secret,
  backup_codes,
  enabled,
  verified,
  created_at,
  updated_at
)
VALUES (
  '947d9e41-8d7b-4604-978b-4cb2819b8794',
  'PLACEHOLDER_SECRET_TO_BE_GENERATED', -- Will be replaced by actual secret
  ARRAY[
    'BACKUP-001-XXXXXX',
    'BACKUP-002-XXXXXX',
    'BACKUP-003-XXXXXX',
    'BACKUP-004-XXXXXX',
    'BACKUP-005-XXXXXX',
    'BACKUP-006-XXXXXX',
    'BACKUP-007-XXXXXX',
    'BACKUP-008-XXXXXX'
  ], -- Will be replaced with actual codes
  false, -- Start disabled until verified
  false, -- Not verified yet
  NOW(),
  NOW()
)
ON CONFLICT (user_id) DO UPDATE SET
  updated_at = NOW();

-- Step 3: Log security event
INSERT INTO security_audit_log (
  event_type,
  user_id,
  details,
  created_at
)
VALUES (
  'mfa_setup_initiated',
  '947d9e41-8d7b-4604-978b-4cb2819b8794',
  jsonb_build_object(
    'action', 'MFA setup initiated',
    'user_email', 'operations@falconeyegroup.net',
    'initiated_by', 'system_admin',
    'timestamp', NOW()
  ),
  NOW()
);

-- Verify the setup
SELECT 
  um.user_id,
  u.email,
  u.raw_user_meta_data->>'full_name' as full_name,
  um.enabled as mfa_enabled,
  um.verified as mfa_verified,
  um.created_at as mfa_setup_at
FROM user_mfa um
JOIN auth.users u ON um.user_id = u.id
WHERE um.user_id = '947d9e41-8d7b-4604-978b-4cb2819b8794';

-- ========================================
-- 📱 MANUAL STEPS REQUIRED:
-- ========================================
-- 
-- After running this SQL, the user must:
--
-- 1. Login to the system as operations@falconeyegroup.net
-- 2. Navigate to Profile → Security Settings
-- 3. Click "Enable Two-Factor Authentication"
-- 4. Scan the QR code with Google Authenticator or Authy app
-- 5. Enter the 6-digit verification code
-- 6. Save the 8 backup codes in a secure location
-- 
-- OR use the API endpoint:
-- POST /api/auth/mfa
-- Body: { "action": "setup" }
-- 
-- This will generate:
-- - TOTP secret
-- - QR code for authenticator app
-- - 8 backup recovery codes
-- ========================================







