#!/usr/bin/env tsx
/**
 * RBAC Drift Analysis Script
 * 
 * Analyzes permission drift by comparing:
 * 1. Permissions used in code (via withRBAC calls)
 * 2. Permissions seeded in database
 * 3. Permissions documented
 * 
 * Generates: docs/rbac_drift_report.md
 */

import { createClient } from '@supabase/supabase-js';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { glob } from 'glob';

// Load environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || '';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('❌ Missing Supabase credentials');
  console.error('Required: NEXT_PUBLIC_SUPABASE_URL or SUPABASE_URL');
  console.error('Required: SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface Permission {
  name: string;
  resource: string;
  action: string;
  scope: string;
  description?: string;
}

/**
 * Extract permissions from codebase
 */
async function extractPermissionsFromCode(): Promise<Set<string>> {
  const permissions = new Set<string>();
  
  // Search for withRBAC calls in API routes and server components
  const patterns = [
    'app/**/api/**/*.{ts,tsx}',
    'app/**/route.{ts,tsx}',
    'app/**/page.{ts,tsx}',
    'src/**/*.{ts,tsx}',
  ];
  
  for (const pattern of patterns) {
    try {
      const files = await glob(pattern, { cwd: process.cwd() });
      for (const file of files) {
        try {
          const content = readFileSync(file, 'utf-8');
          // Match withRBAC('permission:name') or withRBAC("permission:name")
          const matches = content.matchAll(/withRBAC\(['"]([^'"]+)['"]\)/g);
          for (const match of matches) {
            permissions.add(match[1]);
          }
        } catch (err) {
          // Skip files that can't be read
        }
      }
    } catch (err) {
      // Skip patterns that don't match
    }
  }
  
  return permissions;
}

/**
 * Fetch permissions from database
 */
async function fetchDatabasePermissions(): Promise<Permission[]> {
  try {
    const { data, error } = await supabase
      .from('permissions')
      .select('name, resource, action, scope, description');
    
    if (error) {
      console.error('❌ Error fetching permissions:', error.message);
      return [];
    }
    
    return data || [];
  } catch (error) {
    console.error('❌ Error connecting to database:', error);
    return [];
  }
}

/**
 * Generate drift report
 */
async function generateDriftReport() {
  console.log('🔍 Analyzing RBAC drift...\n');
  
  // Extract permissions from code
  const codePermissions = await extractPermissionsFromCode();
  console.log(`📝 Found ${codePermissions.size} unique permissions in code`);
  
  // Fetch permissions from database
  const dbPermissions = await fetchDatabasePermissions();
  const dbPermissionNames = new Set(dbPermissions.map(p => p.name));
  console.log(`💾 Found ${dbPermissions.length} permissions in database\n`);
  
  // Find P0 critical issues (used in code but not in DB)
  const p0Issues = Array.from(codePermissions).filter(p => !dbPermissionNames.has(p));
  
  // Find P2 issues (in DB but not used in code)
  const p2Issues = dbPermissions.filter(p => !codePermissions.has(p.name));
  
  // Generate report
  const timestamp = new Date().toISOString();
  const report = `# 🛡️ RBAC Drift Report

Generated: ${timestamp}

## 📊 Executive Summary

- **Total Seeded Permissions**: ${dbPermissions.length}
- **Total Used in Code**: ${codePermissions.size}
- **P0 Critical Issues**: ${p0Issues.length}
- **P2 Low Priority Issues**: ${p2Issues.length}

## 🔴 P0 Critical Issues (Used in Code but NOT Seeded)

${p0Issues.length === 0 
  ? '✅ No critical issues found' 
  : p0Issues.map(p => `- \`${p}\``).join('\n')}

## 🟡 P2 Low Priority Issues

### Seeded but NOT Used in Code

${p2Issues.length === 0 
  ? '✅ No unused permissions found' 
  : p2Issues.map(p => `- \`${p.name}\``).join('\n')}

## 📋 Recommendations

${p0Issues.length > 0 
  ? `### Immediate Action Required\n\n${p0Issues.length} permission(s) are used in code but not seeded in the database. These must be added to prevent runtime errors.\n\nRun: \`npm run rbac:fix:simple\` to apply fixes.` 
  : ''}

${p2Issues.length > 0 
  ? `### Cleanup Opportunities\n\n${p2Issues.length} permission(s) are seeded but not used. Consider removing them to reduce complexity.` 
  : ''}

---
*Report generated by RBAC Drift Analysis Script*
`;
  
  // Ensure docs directory exists
  const docsDir = join(process.cwd(), 'docs');
  if (!existsSync(docsDir)) {
    require('fs').mkdirSync(docsDir, { recursive: true });
  }
  
  // Write report
  const reportPath = join(docsDir, 'rbac_drift_report.md');
  writeFileSync(reportPath, report, 'utf-8');
  console.log(`✅ Report generated: ${reportPath}\n`);
  
  // Print summary
  if (p0Issues.length > 0) {
    console.log(`🚨 P0 Critical Issues: ${p0Issues.length}`);
    p0Issues.forEach(p => console.log(`   - ${p}`));
    console.log('');
    process.exit(1);
  } else {
    console.log('✅ No P0 critical issues found');
    process.exit(0);
  }
}

// Run analysis
generateDriftReport().catch(error => {
  console.error('❌ Fatal error:', error);
  process.exit(1);
});

